version: '3.8'

services:
  app:
    container_name: java-eats-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src:ro

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=java_eats
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"


