version: '3.8'

services:
  app:
    container_name: java-eats-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - redis
    networks:
        - mynet

  postgres:
    image: postgis/postgis:15-3.4    # it contains PostGIS
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=java_eats
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@javaeats.dev
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - mynet


networks:
  mynet:
    driver: bridge

volumes:
  pgdata:
  redisdata:
  pgadmindata:

